server:
  port: 8767

spring:
  application:
    name: eureka-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

zuul:
  routes:
    # 设置服务a 路径名称 随便起
    service-a:
      path: /eureka-consumer/**
      # 这里写a服务的注册名字
      serviceId: eureka-consumer