server:
  port: 8765

spring:
  application:
    name: eureka-producer
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
  redis:
    # 地址
    #    host: 127.0.0.1
    host: 192.168.0.220
    # 端口，默认为6379
    port: 6379
    # 密码
    password: 123456
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）SysLogininforMapper
        max-wait: -1ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


mybatis-plus:
  global-config:
    db-config:
      db-type: mysql
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.example.**.pojo
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

